// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: province.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAllProvinces
type GetAllProvincesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*ProvinceData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllProvincesResponse) Reset() {
	*x = GetAllProvincesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProvincesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProvincesResponse) ProtoMessage() {}

func (x *GetAllProvincesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProvincesResponse.ProtoReflect.Descriptor instead.
func (*GetAllProvincesResponse) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllProvincesResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAllProvincesResponse) GetData() []*ProvinceData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetProvinceByID
type GetProvinceByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *GetProvinceByIDInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetProvinceByIDRequest) Reset() {
	*x = GetProvinceByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvinceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceByIDRequest) ProtoMessage() {}

func (x *GetProvinceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProvinceByIDRequest) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{1}
}

func (x *GetProvinceByIDRequest) GetRequest() *GetProvinceByIDInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetProvinceByIDInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProvinceByIDInput) Reset() {
	*x = GetProvinceByIDInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvinceByIDInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceByIDInput) ProtoMessage() {}

func (x *GetProvinceByIDInput) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceByIDInput.ProtoReflect.Descriptor instead.
func (*GetProvinceByIDInput) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{2}
}

func (x *GetProvinceByIDInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProvinceByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *ProvinceData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetProvinceByIDResponse) Reset() {
	*x = GetProvinceByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvinceByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceByIDResponse) ProtoMessage() {}

func (x *GetProvinceByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProvinceByIDResponse) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{3}
}

func (x *GetProvinceByIDResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetProvinceByIDResponse) GetData() *ProvinceData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetProvincesByIDs
type GetProvincesByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *GetProvincesByIDsInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetProvincesByIDsRequest) Reset() {
	*x = GetProvincesByIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvincesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvincesByIDsRequest) ProtoMessage() {}

func (x *GetProvincesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvincesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetProvincesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{4}
}

func (x *GetProvincesByIDsRequest) GetRequest() *GetProvincesByIDsInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetProvincesByIDsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProvincesByIDsInput) Reset() {
	*x = GetProvincesByIDsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvincesByIDsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvincesByIDsInput) ProtoMessage() {}

func (x *GetProvincesByIDsInput) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvincesByIDsInput.ProtoReflect.Descriptor instead.
func (*GetProvincesByIDsInput) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{5}
}

func (x *GetProvincesByIDsInput) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetProvincesByIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*ProvinceData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetProvincesByIDsResponse) Reset() {
	*x = GetProvincesByIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvincesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvincesByIDsResponse) ProtoMessage() {}

func (x *GetProvincesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvincesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetProvincesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{6}
}

func (x *GetProvincesByIDsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetProvincesByIDsResponse) GetData() []*ProvinceData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Base Data
type ProvinceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvinceID   string `protobuf:"bytes,1,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	ProvinceName string `protobuf:"bytes,2,opt,name=provinceName,proto3" json:"provinceName,omitempty"`
	IslandID     string `protobuf:"bytes,3,opt,name=islandID,proto3" json:"islandID,omitempty"`
}

func (x *ProvinceData) Reset() {
	*x = ProvinceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceData) ProtoMessage() {}

func (x *ProvinceData) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceData.ProtoReflect.Descriptor instead.
func (*ProvinceData) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{7}
}

func (x *ProvinceData) GetProvinceID() string {
	if x != nil {
		return x.ProvinceID
	}
	return ""
}

func (x *ProvinceData) GetProvinceName() string {
	if x != nil {
		return x.ProvinceName
	}
	return ""
}

func (x *ProvinceData) GetIslandID() string {
	if x != nil {
		return x.IslandID
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message []string `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{8}
}

func (x *Header) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Header) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

type OptionalString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	HasSet bool   `protobuf:"varint,2,opt,name=hasSet,proto3" json:"hasSet,omitempty"`
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_province_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_province_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_province_proto_rawDescGZIP(), []int{9}
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionalString) GetHasSet() bool {
	if x != nil {
		return x.HasSet
	}
	return false
}

var File_province_proto protoreflect.FileDescriptor

var file_province_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x06, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x61, 0x73, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x68, 0x61, 0x73, 0x53, 0x65, 0x74, 0x32, 0x9b, 0x02, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_province_proto_rawDescOnce sync.Once
	file_province_proto_rawDescData = file_province_proto_rawDesc
)

func file_province_proto_rawDescGZIP() []byte {
	file_province_proto_rawDescOnce.Do(func() {
		file_province_proto_rawDescData = protoimpl.X.CompressGZIP(file_province_proto_rawDescData)
	})
	return file_province_proto_rawDescData
}

var file_province_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_province_proto_goTypes = []interface{}{
	(*GetAllProvincesResponse)(nil),   // 0: province.GetAllProvincesResponse
	(*GetProvinceByIDRequest)(nil),    // 1: province.GetProvinceByIDRequest
	(*GetProvinceByIDInput)(nil),      // 2: province.GetProvinceByIDInput
	(*GetProvinceByIDResponse)(nil),   // 3: province.GetProvinceByIDResponse
	(*GetProvincesByIDsRequest)(nil),  // 4: province.GetProvincesByIDsRequest
	(*GetProvincesByIDsInput)(nil),    // 5: province.GetProvincesByIDsInput
	(*GetProvincesByIDsResponse)(nil), // 6: province.GetProvincesByIDsResponse
	(*ProvinceData)(nil),              // 7: province.ProvinceData
	(*Header)(nil),                    // 8: province.Header
	(*OptionalString)(nil),            // 9: province.OptionalString
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_province_proto_depIdxs = []int32{
	8,  // 0: province.GetAllProvincesResponse.header:type_name -> province.Header
	7,  // 1: province.GetAllProvincesResponse.data:type_name -> province.ProvinceData
	2,  // 2: province.GetProvinceByIDRequest.request:type_name -> province.GetProvinceByIDInput
	8,  // 3: province.GetProvinceByIDResponse.header:type_name -> province.Header
	7,  // 4: province.GetProvinceByIDResponse.data:type_name -> province.ProvinceData
	5,  // 5: province.GetProvincesByIDsRequest.request:type_name -> province.GetProvincesByIDsInput
	8,  // 6: province.GetProvincesByIDsResponse.header:type_name -> province.Header
	7,  // 7: province.GetProvincesByIDsResponse.data:type_name -> province.ProvinceData
	10, // 8: province.ProvinceService.GetAllProvinces:input_type -> google.protobuf.Empty
	1,  // 9: province.ProvinceService.GetProvinceByID:input_type -> province.GetProvinceByIDRequest
	4,  // 10: province.ProvinceService.GetProvincesByIDs:input_type -> province.GetProvincesByIDsRequest
	0,  // 11: province.ProvinceService.GetAllProvinces:output_type -> province.GetAllProvincesResponse
	3,  // 12: province.ProvinceService.GetProvinceByID:output_type -> province.GetProvinceByIDResponse
	6,  // 13: province.ProvinceService.GetProvincesByIDs:output_type -> province.GetProvincesByIDsResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_province_proto_init() }
func file_province_proto_init() {
	if File_province_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_province_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProvincesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvinceByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvinceByIDInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvinceByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvincesByIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvincesByIDsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvincesByIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvinceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_province_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_province_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_province_proto_goTypes,
		DependencyIndexes: file_province_proto_depIdxs,
		MessageInfos:      file_province_proto_msgTypes,
	}.Build()
	File_province_proto = out.File
	file_province_proto_rawDesc = nil
	file_province_proto_goTypes = nil
	file_province_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProvinceServiceClient is the client API for ProvinceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvinceServiceClient interface {
	GetAllProvinces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllProvincesResponse, error)
	GetProvinceByID(ctx context.Context, in *GetProvinceByIDRequest, opts ...grpc.CallOption) (*GetProvinceByIDResponse, error)
	GetProvincesByIDs(ctx context.Context, in *GetProvincesByIDsRequest, opts ...grpc.CallOption) (*GetProvincesByIDsResponse, error)
}

type provinceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvinceServiceClient(cc grpc.ClientConnInterface) ProvinceServiceClient {
	return &provinceServiceClient{cc}
}

func (c *provinceServiceClient) GetAllProvinces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllProvincesResponse, error) {
	out := new(GetAllProvincesResponse)
	err := c.cc.Invoke(ctx, "/province.ProvinceService/GetAllProvinces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) GetProvinceByID(ctx context.Context, in *GetProvinceByIDRequest, opts ...grpc.CallOption) (*GetProvinceByIDResponse, error) {
	out := new(GetProvinceByIDResponse)
	err := c.cc.Invoke(ctx, "/province.ProvinceService/GetProvinceByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) GetProvincesByIDs(ctx context.Context, in *GetProvincesByIDsRequest, opts ...grpc.CallOption) (*GetProvincesByIDsResponse, error) {
	out := new(GetProvincesByIDsResponse)
	err := c.cc.Invoke(ctx, "/province.ProvinceService/GetProvincesByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvinceServiceServer is the server API for ProvinceService service.
type ProvinceServiceServer interface {
	GetAllProvinces(context.Context, *emptypb.Empty) (*GetAllProvincesResponse, error)
	GetProvinceByID(context.Context, *GetProvinceByIDRequest) (*GetProvinceByIDResponse, error)
	GetProvincesByIDs(context.Context, *GetProvincesByIDsRequest) (*GetProvincesByIDsResponse, error)
}

// UnimplementedProvinceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProvinceServiceServer struct {
}

func (*UnimplementedProvinceServiceServer) GetAllProvinces(context.Context, *emptypb.Empty) (*GetAllProvincesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProvinces not implemented")
}
func (*UnimplementedProvinceServiceServer) GetProvinceByID(context.Context, *GetProvinceByIDRequest) (*GetProvinceByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvinceByID not implemented")
}
func (*UnimplementedProvinceServiceServer) GetProvincesByIDs(context.Context, *GetProvincesByIDsRequest) (*GetProvincesByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvincesByIDs not implemented")
}

func RegisterProvinceServiceServer(s *grpc.Server, srv ProvinceServiceServer) {
	s.RegisterService(&_ProvinceService_serviceDesc, srv)
}

func _ProvinceService_GetAllProvinces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).GetAllProvinces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/province.ProvinceService/GetAllProvinces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).GetAllProvinces(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_GetProvinceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvinceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).GetProvinceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/province.ProvinceService/GetProvinceByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).GetProvinceByID(ctx, req.(*GetProvinceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_GetProvincesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvincesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).GetProvincesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/province.ProvinceService/GetProvincesByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).GetProvincesByIDs(ctx, req.(*GetProvincesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProvinceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "province.ProvinceService",
	HandlerType: (*ProvinceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllProvinces",
			Handler:    _ProvinceService_GetAllProvinces_Handler,
		},
		{
			MethodName: "GetProvinceByID",
			Handler:    _ProvinceService_GetProvinceByID_Handler,
		},
		{
			MethodName: "GetProvincesByIDs",
			Handler:    _ProvinceService_GetProvincesByIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "province.proto",
}
